### ISSUE TITLE
ValueError: Invalid bbox

### ISSUE THREAD

**Issue by akhilman** [anntzer/mplcairo#8]
I have error message when try to run my app with mplcairo from git master.

```
Traceback (most recent call last):                                                                                                            
  File "/home/ildar/slivoglot-2/thirdparty/matplotlib/lib/matplotlib/cbook/__init__.py", line 216, in process                                 
    func(*args, **kwargs)                                                                                                                     
  File "/home/ildar/slivoglot-2/thirdparty/matplotlib/lib/matplotlib/widgets.py", line 1401, in clear                                         
    self.canvas.copy_from_bbox(self.canvas.figure.bbox))                                                                                      
  File "/opt/slivoglot-2.dev/lib/python3.6/site-packages/mplcairo/base.py", line 237, in copy_from_bbox                                       
    return self.get_renderer(_draw_if_new=True).copy_from_bbox(bbox)                                                                          
ValueError: Invalid bbox  

ipdb> args                                                                                                                                    
self = <gtk.FigureCanvasGTKCairo object at 0xee924af4 (mplcairo+gtk+FigureCanvasGTKCairo at 0x8f7da48)>                                       
bbox = <matplotlib.transforms.TransformedBbox object at 0xee9255cc> 

ipdb> bbox.corners()
array([[  0.,   0.],
       [  0., 627.],
       [972.,   0.],
       [972., 627.]])
```

Sorry, but I have no small example.

**Comment by anntzer** [comment]
The relevant snippet is
```
  auto const& state = get_additional_state();
  auto const
    & x0 = int(std::floor(bbox.attr("x0").cast<double>())),
    & x1 = int(std::ceil(bbox.attr("x1").cast<double>())),
    // Invert y-axis.
    & y0 = int(std::floor(state.height - bbox.attr("y1").cast<double>())),
    & y1 = int(std::ceil(state.height - bbox.attr("y0").cast<double>()));
  if (!(0 <= x0 && x0 <= x1 && x1 <= state.width
        && 0 <= y0 && y0 <= y1 && y1 <= state.height)) {
    throw std::invalid_argument("Invalid bbox");
  }
```
where `state.width` and `state.height` are the canvas width and height.  What are they, in your case?

**Comment by akhilman** [comment]
```
ValueError: Cannot copy TransformedBbox(
    Bbox(x0=0.0, y0=0.0, x1=9.72, y1=6.27),
    Affine2D(
        [[100.   0.   0.]
         [  0. 100.   0.]
         [  0.   0.   1.]])) from canvas of width 972.0 and height 627.0
```

**Comment by anntzer** [comment]
Some floating point inaccuracy in converting the float limits to ints, I guess... Try
```
@@ -1333,14 +1333,16 @@ Region GraphicsContextRenderer::copy_from_bbox(py::object bbox)
   // Use ints to avoid a bunch of warnings below.
   auto const& state = get_additional_state();
   auto const
-    & x0 = int(std::floor(bbox.attr("x0").cast<double>())),
-    & x1 = int(std::ceil(bbox.attr("x1").cast<double>())),
+    & x0 = int(std::ceil(bbox.attr("x0").cast<double>())),
+    & x1 = int(std::floor(bbox.attr("x1").cast<double>())),
     // Invert y-axis.
-    & y0 = int(std::floor(state.height - bbox.attr("y1").cast<double>())),
-    & y1 = int(std::ceil(state.height - bbox.attr("y0").cast<double>()));
+    & y0 = int(std::ceil(state.height - bbox.attr("y1").cast<double>())),
+    & y1 = int(std::floor(state.height - bbox.attr("y0").cast<double>()));
   if (!(0 <= x0 && x0 <= x1 && x1 <= state.width
         && 0 <= y0 && y0 <= y1 && y1 <= state.height)) {
```
(and perhaps print `bbox.attr("x0").cast<double>()` and the others for good measure).

**Comment by akhilman** [comment]
Now all works fine. Thanks.

**Comment by anntzer** [comment]
Pushed fix as https://github.com/anntzer/mplcairo/commit/6c9e6a363e433c804c2d3ab8a45effbf99d98e31.
Thanks for the report!
